version: '3.8'
services:
  arma3:
    build: .
    image: ghcr.io/brettmayson/arma3server/arma3server:latest
    platform: linux/amd64
    container_name: arma3
    network_mode: host
    volumes:
      - './arma3/missions:/arma3/mpmissions'
      - './arma3/configs:/arma3/configs'
      - './arma3/mods:/arma3/mods'
      - './arma3/servermods:/arma3/servermods'
    
      - './dlc/jets:/arma3/addons'
      - './dlc/jets:/arma3/jets'
      - './dlc/addons:/arma3/addons'
      - './dlc/heli:/arma3/heli'
      - './dlc/orange:/arma3/orange'
      - './dlc/argo:/arma3/argo'
      - './dlc/enoch:/arma3/enoch'
    environment:
      ARMA_BINARY: "${ARMA_BINARY}"
      ARMA_CDLC: "${ARMA_CDLC}"
      ARMA_CONFIG: "${ARMA_CONFIG}"
      ARMA_LIMITFPS: "${ARMA_LIMITFPS}"
      ARMA_PARAMS: "${ARMA_PARAMS}"
      ARMA_PROFILE: "${ARMA_PROFILE}"
      ARMA_WORLD: "${ARMA_WORLD}"
      HEADLESS_CLIENTS: "${HEADLESS_CLIENTS}"
      HEADLESS_CLIENTS_PROFILE: "${HEADLESS_CLIENTS_PROFILE}"
      MODS_LOCAL: "${MODS_LOCAL}"
      MODS_PRESET: "${MODS_PRESET}"
      PORT: "${PORT}"
      STEAM_BRANCH: "${STEAM_BRANCH}"
      STEAM_BRANCH_PASSWORD: "${STEAM_BRANCH_PASSWORD}"      
      STEAM_PASSWORD: "${STEAM_PASSWORD}"
      STEAM_USER: "${STEAM_USER}"
    restart: unless-stopped
